### ISSUE TITLE
Want to get a list of localizations with the corresponding density values.

### ISSUE THREAD

**Issue by bbrenner2** [flevet/SR-Tesseler#1]
I did uploaded a csv localization file to SR-Tesseler and created Voronoi polygons. Now I would like to export the density of each localization with its corresponding x,y localization. I found that if I just directly save the density values to a txt, they do not seem to correspond to the order in which the data was input.

**Comment by flevet** [comment]
Indeed, this is not something that is currently possible with SR-Tesseler. It is possible in PoCA if the index of the localization is a feature in the localization file.
